x = np.linspace(0, 2, 100)
fig, ax = plt.subplots(figsize=(5, 2.7), layout='constrained')
ax.plot(x, x, label='Linear')
ax.plot(x, x**2, label='Quadratic')
ax.plot(x, x**3, label='Cubic')
ax.legend()
ax.set_title('Simple Plot')
plt.show()
